# ~/.config/lyrics/lyrics.toml
# 
[player-filter]
except = ["browser", "video", "screen-cast", "chromium", "firefox"]
only = []

[ui]
title = true
time = false
progress_bar = true

[sources]
netease = true
qq = true
kugou = true
